{% set name = "sgqlc" %}
{% set version = "14.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 71364af1884cf7e402cfd35058dafbcddf825b986898f68e6dd5195e2cd0472d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - sgqlc-codegen = sgqlc.codegen:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - graphql-core

test:
  imports:
    - sgqlc
  requires:
    - pip
  commands:
    - pip check
    - sgqlc-codegen --help

about:
  home: https://sgqlc.readthedocs.io/
  license: ISC
  license_file: LICENSE
  summary: Simple GraphQL Client
  dev_url: https://github.com/profusion/sgqlc

extra:
  recipe-maintainers:
    - hoechenberger
